name: "Publicar a NPM"

on:
  # release:
  #   types: [published]
  push:
    branches:
      - master

jobs:
  release:
    name: "Publicar"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}