name: "Publicar a NPM"

on:
  # release:
  #   types: [published]
  push:
    branches:
      - master

jobs:
  release:
    name: "Publicar"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}